title: 20x20x20
email: vikpek@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  challenge: 20 games in 20 month in 20 hours each.

  Development diary of relaxed and yet ambitious challenge to grow as a game developer. 
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vikpek
github_username:  vikpek

# Build settings
theme: minima
plugins:
  - jekyll-feed
